# Generated by Django 5.0 on 2024-01-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="creator",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
