# Generated by Django 5.0 on 2024-01-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0004_todo_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
